version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: game-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'game-api'
      MYSQL_ROOT_PASSWORD: 'root123'
    ports:
      - '3309:3306'
    expose:
      - '3309'
    volumes:
      - db-game:/var/lib/mysql

  game-api: 
    image: dihhcassio/game-api:v1
    ports:
        - '5000:80'
    environment:
        DBHOST: "game-mysql"
        DBPORT: "3306"
        DBUSER: "root"
        DBPASSWORD: "root123"
        DBNAME: "game-api" 
    depends_on:
      - db
    
  game-webapp: 
    image: game-webapp:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - '5001:80'
    depends_on:
      - game-api

volumes:
  db-game:
